FROM alpine:{{ alpine_version }}

ARG WORDPRESS_DB_USER \
    WORDPRESS_DB_PASSWORD \
    WORDPRESS_DB_HOST \
    WORDPRESS_DB_NAME

RUN apk update && apk upgrade && apk add --update --no-cache \
    gcc \
    make \
	wget \
    curl \
    musl-dev \
	php81 \
    php81-gd \
    php81-dom \
	php81-fpm \
    php81-xml \
    php81-zip \
    php81-phar \
    php81-curl \
    php81-exif \
    php81-json \
    php81-intl \
    php81-iconv \
    php81-mysqli \
    php81-sodium \
    php81-openssl \
    php81-fileinfo \
    php81-mbstring \
    php81-pecl-imagick

COPY update_wpconfig.sh /tmp
COPY wp-config.php /tmp

RUN mkdir -p /var/www/html/ && \
    wget -qO- https://wordpress.org/latest.tar.gz | tar xz -C /var/www/html/ && \
    sh /tmp/update_wpconfig.sh && \
    cat /tmp/wp-config.php >> /var/www/html/wordpress/wp-config.php && \
    echo "listen = {{ wordpress_port }}" >> /etc/php81/php-fpm.d/www.conf

EXPOSE {{ wordpress_port }}

CMD ["php-fpm81", "--nodaemonize"]
