---
- name: Install Docker dependencies
  tags: [docker]
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Create keyrings directory
  tags: [docker]
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: Add Docker GPG key
  tags: [docker]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  tags: [docker]
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  tags: [docker]
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: Enable Docker service
  tags: [docker]
  service:
    name: docker
    state: started
    enabled: yes

- name: Add main user to docker group
  tags: [docker]
  user:
    name: "{{ vault_main_user }}"
    groups: docker
    append: yes

- name: Install lazydocker
  tags: [docker, lazydocker]
  shell: curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

- name: Create ~/.local/bin
  tags: [docker, lazydocker]
  file:
    path: /home/{{ vault_main_user }}/.local/bin
    state: directory
    owner: "{{ vault_main_user }}"
    group: "{{ vault_main_user }}"
    mode: 0755

- name: Copy lazydocker to main_user
  tags: [docker, lazydocker]
  copy:
    src: /root/.local/bin/lazydocker
    dest: /home/{{ vault_main_user }}/.local/bin/lazydocker
    owner: "{{ vault_main_user }}"
    group: "{{ vault_main_user }}"
    mode: 0755
    remote_src: yes

- name: Add ~/.local/bin to PATH
  tags: [docker, lazydocker]
  lineinfile:
    path: /home/{{ vault_main_user }}/.zshrc
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: yes
    insertafter: EOF
